### ISSUE TITLE
consider metadata: sending it to the pod on edn values.

### ISSUE THREAD

**Issue by retrogradeorbit** [babashka/babashka.pods#13]
Some clojure code relies on metadata being present on the values. We should be able to send this metadata on edn back and forth between pod and client.

```
Crispin  11:08 PM
ok that NPE was a full rabbit hole
but led to an interesting discovery
metadata doesn't travel with the edn data
and metadata can be used/abused in non visible ways
so I had a zipper being created in the pod side
then used on the bb side
and I didn't know this, but clojure.zip zippers use metadata to make decisions!!!!
```

```
borkdude  11:11 PM
if you're using EDN, you're already using clojure on both sides probably
https://clojuredocs.org/clojure.core/*print-meta*
user=> (binding [*print-meta* true] (pr-str ^{:a 1} [1 2 3]))
"^{:a 1} [1 2 3]"
user=> (meta (clojure.edn/read-string (binding [*print-meta* true] (pr-str ^{:a 1} [1 2 3]))))
{:a 1}
...
but we have to be careful... e.g. when it prints namespaces of vars, etc... that won't work... :slightly_smiling_face:
but in general, vars get resolved anyway before being sent
```

**Comment by borkdude** [comment]
Pods can already choose to send EDN with metadata back to the pod client using `*print-meta*`.

Making sending metadata the default could potentially be dangerous since not everything that's `pr-str`-ed can be read as valid EDN. We'll have to think when and how this can become a problem.

Alternatively, pods can also choose to write client side wrapper functions that coerce their args into EDN with metadata on a case by case basis and send the EDN-ized string to themselves.

**Comment by borkdude** [comment]
I think this can be handled using `*print-meta*` now.
