### ISSUE TITLE
Is there a way of unloading pods?

### ISSUE THREAD

**Issue by zcaudate** [babashka/babashka.pods#17]
With boot pods, it's possible to create a fresh environment, run some code and remove that environment. It this possible with babashka?

**Comment by borkdude** [comment]
@zcaudate There is `unload-pod`: 

https://github.com/babashka/babashka.pods/blob/9036af19573c0f1c5f2d71f9f51afe770c99497e/src/babashka/pods.clj#L8

This isn't documented yet, since the API for this might still change. Could you explain why you need this?

**Comment by zcaudate** [comment]
Okay. I see it.

I don't think it'll support what I had in mind - which is to be able to load and destroy sandboxed environments quickly for multiple users on the web (kind of like a poor man's version of jupyter)

I discussed it here:

https://clojurians.zulipchat.com/#narrow/stream/151924-data-science/topic/goldly.20prototype/near/199441760

**Comment by zcaudate** [comment]
@borkdude I know that a lot of your work is around getting clojure to work with graalvm. Would you know if it's possible to get shim dandy (https://github.com/projectodd/shimdandy) running on native image?

**Comment by borkdude** [comment]
@zcaudate Clojure in general doesn't work on GraalVM, only parts that can be statically compiled. Everything around `eval` doesn't work. This is why I wrote the [Small Clojure Interpreter](https://github.com/borkdude/sci): instead of compiling code, it interprets code and this works in a GraalVM binary. Sci evaluation happens in isolation (the effect of running programs is not visible to the calling runtime, unless you plug in side-effecting functions) and you have control over which functions are and aren't allowed. That might be the closest thing that's possible right now.

**Comment by zcaudate** [comment]
@borkdude that makes a lot of sense. Thanks for the explanation.
